Level 3
edwa1401/oop_bases_challenges pull request #7
Opened 2023-09-16 19:07 UTC by edwa1401

2023-09-19 12:48 UTC, vppuzakov requested changes
👍 тут все верно, кроме третьего - там как будто опечатка - но важно поправить - ведь мы получается не переопределили метод, а сделали еще один

2023-09-19 12:48 UTC, vppuzakov commented on level_3/a_credit_bank_account.py
> +class BankAccount:
👍 верно вынес только часть касающуюся банковского аккаунта

2023-09-19 12:48 UTC, vppuzakov commented on level_3/a_credit_bank_account.py
> +class CreditAccount(BankAccount):
👍 верно вынес только часть касающуюся кредитного аккаунта, остальное поведение он наследует

2023-09-19 12:48 UTC, vppuzakov commented on level_3/a_credit_bank_account.py
> +    akakiy_bank_acc = BankAccount(owner_full_name='Akakiy Akakievich Akakiev', balance=1000.00)
👍 потестил поведение банк аккаунта

2023-09-19 12:48 UTC, vppuzakov commented on level_3/a_credit_bank_account.py
> +    marfa_cred_acc = CreditAccount(owner_full_name='Marfa Ivanova', balance=900.00)
👍 потестил поведение кредитного аккаунта

2023-09-19 12:48 UTC, vppuzakov commented on level_3/b_user_manage.py
> +    def __init__(self) -> None:
👍 отлично, аннотации проставил

2023-09-19 12:48 UTC, vppuzakov commented on level_3/b_user_manage.py
>          self.usernames = []
💡 на поля объекта тоже стоит расставить аннотацию, так как непонятно, что это будет за список, какие значения под капотом

2023-09-19 12:48 UTC, vppuzakov commented on level_3/b_user_manage.py
> +            print('Такого пользователя не существует')
👍 согласно заданию все верно

💡 если такая ситуация ожидаема, лучше проверить наличие username в нашем списке заранее и обойтись без try .. except

💡 заодно можно вернуть результат выполнения bool (удалили или нет) и печать уже в вызывающем коде ниже

2023-09-19 12:48 UTC, vppuzakov commented on level_3/b_user_manage.py
> +    def ban_all_users(self) -> None:
👍 все верно

2023-09-19 12:48 UTC, vppuzakov commented on level_3/b_user_manage.py
> +    users = UserManager()
👍 хорошая проверка того что было в usermanager

2023-09-19 12:48 UTC, vppuzakov commented on level_3/b_user_manage.py
> +    beatles = AdminManager()
👍 проверили admin manager

2023-09-19 12:48 UTC, vppuzakov commented on level_3/b_user_manage.py
> +    reservoir_dogs = SuperAdminManager()
👍 проверили superadminmanager

2023-09-19 12:48 UTC, vppuzakov commented on level_3/c_text_processor.py
> +    def __init__(self, text: str) -> None:
👍 красиво, аннотации на месте

2023-09-19 12:48 UTC, vppuzakov commented on level_3/c_text_processor.py
> +        return super().summarize() + f', total number of words in the text: {len(words)}'
👍 да, можно переиспользовать родительский метод
💡 от плюса при конкатенации строк лучше было бы избавится - сформировать нужную строку сразу через `format`
💡 сложно и ведет к ошибкам в f-string использовать что-то сложнее чем переменная - поэтому формат тут лучший выбор

2023-09-19 12:48 UTC, vppuzakov commented on level_3/c_text_processor.py
> +    def summaryze(self) -> str:
🔴 метод с другим названием - получается не переопределен

2023-09-19 12:48 UTC, vppuzakov commented on level_3/c_text_processor.py
> +        words = re.findall(r'\b\w+\b', self.text)
👍 заморочился за регулярки, можно было б и сплитом обычным =)

2023-09-19 12:48 UTC, vppuzakov commented on level_3/d_alcohol_product.py
> +    def __init__(self, title: str, price: decimal.Decimal, stock_quantity: decimal.Decimal) -> None:
👍 аннотации на месте

2023-09-19 12:48 UTC, vppuzakov commented on level_3/d_alcohol_product.py
> +        if  current_hour > 5 and current_hour < 23:
👍 в целом верно, но лучше вывернуть условие - сначала проверить и вернуть False потом спокойно вернуть проверку родителя и else не нужен будет

2023-09-19 12:48 UTC, vppuzakov commented on level_3/d_alcohol_product.py
> +    cucumber = Product(title='огурцы', price=100.01, stock_quantity=1.050)
👍 проверки на месте

2023-09-19 13:13 UTC, edwa1401 commented on level_3/b_user_manage.py
> +            print('Такого пользователя не существует')
💡 заодно можно вернуть результат выполнения bool (удалили или нет) и печать уже в вызывающем коде ниже

не очень понял про bool. Написал так:

class AdminManager(UserManager):
    def ban_username(self, username: str) -> None | str:
        if username in self.usernames:
            self.usernames.remove(username)
        else:
            print('Такого пользователя не существует')

2023-09-21 22:07 UTC, vppuzakov approved these changes
👍 approve еще в прошлый раз - вмержил бы, одно критично изменение за `summaryze` -> `summarize` не поправил

2023-09-21 22:07 UTC, vppuzakov commented on level_3/b_user_manage.py
> +            print('Такого пользователя не существует')
вариант верный, только ничего не вернет - в аннотации отразить. В пр изменений не вижу этих.

2023-09-21 22:07 UTC, vppuzakov commented on level_3/c_text_processor.py
> +        text_length=super().summarize(),
👍

2023-09-21 22:07 UTC, vppuzakov commented on level_3/c_text_processor.py
> +        return '{text_length} {num_words}'.format(
💡 лучше не мешать string.format и f-string потом

2023-09-21 22:07 UTC, vppuzakov commented on level_3/d_alcohol_product.py
> +        if  current_hour < 5 and current_hour > 23:
👍

2023-09-22 07:55 UTC, merged